### ISSUE TITLE
org-refile 

### ISSUE THREAD

**Issue by slk500** [fuxialexander/org-pdftools#20]
GNU Emacs 27.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2019-09-28, Org mode version 9.3.6. I was trying to install org-pdftools.el and It failed on line L33 (require 'org-refile). he cant find this package. I commented out this line and then everything went smooth.

**Comment by Ramapitecus** [comment]
The files have been moved to `org.el` so this line is not needed anymore.

**Comment by fuxialexander** [comment]
Can you please try whether it works now?

**Comment by gav451** [comment]
GNU Emacs 27.0.90 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.13, cairo version 1.16.0) of 2020-03-04 with https://code.orgmode.org/bzg/org-mode/commits/master.
Indeed, the emacs installed file `/usr/share/emacs/27.090/lisp/org/lisp/org.el` contains the `(defcustom org-directory ...)` form.
However, the git repository (that I use) has a file `org/lisp/org-refile.el`   containing the `(defcustom org-directory ...)` form instead of `org/lib/org.el`.
Adding  `(require org-refile nil t)` will OK in case `org-refile.el` exists and in case `org-refile.el` has been moved into `org.el`.

**Comment by fuxialexander** [comment]
@gav451 just added it

**Comment by slk500** [comment]
it works, thank you
