### ISSUE TITLE
Insert precise note replaces text with icons

### ISSUE THREAD

**Issue by workcomplete** [fuxialexander/org-pdftools#71]
As the title says, text copied from the pdf annotations is replaced by icons when it is sent to the org-noter document using org-pdftools. I don't get this behaviour in any other context in emacs. See attached image. Thanks in advance for any advice or insight!
![Screen Shot 2021-05-06 at 7 05 10 AM](https://user-images.githubusercontent.com/77472800/117312639-0af38600-ae3a-11eb-8842-bfa9480e20bc.png)

**Comment by Charlie-Gordon** [comment]
Hi, just to share some insight, I think the "replace text with icons" part is doable by using the text/overlay property `display` [(see its info node)](https://www.gnu.org/software/emacs/manual/html_node/elisp/Display-Property.html) to ["replace"](https://www.gnu.org/software/emacs/manual/html_node/elisp/Replacing-Specs.html) the text by displaying our  icons on the buffer instead but, I want you to be more specific about how the icons on your screen capture are decided, do they have some sort of a cryptic meaning or pattern to them or just randomly selected? And why do you want them in the first place? Is it because the annotation text are too long?

**Comment by workcomplete** [comment]
The issue was that when text was copied from the PDF to the notes buffer some of the letters and numbers became icons. The desired behaviour was that it remained text. After working with more pdf's I'm pretty sure this was actually and issue with my OCR engine and not emacs. Closing this.
